export const DELETE_FRIEND = 'DELETE_FRIEND';
export const ADD_FRIEND = 'ADD_FRIEND';


export const ADD_FRIENDS = 'ADD_FRIENDS';
export const ADD_FRIENDS_SUCCESS = 'ADD_FRIENDS_SUCCESS';
export const ADD_FRIENDS_FAILURE = 'ADD_FRIENDS_FAILURE';


export const EDIT_FRIEND_BY_ID = 'EDIT_FRIEND_BY_ID';
export const GET_FRIEND_BY_ID = "GET_FRIEND_BY_ID";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
